//
// HPB bot - botman's High Ping Bastard bot
//
// (http://planethalflife.com/botman/)
//
// linkfunc.cpp
//

#include "extdll.h"
#include "util.h"
#include "cbase.h"

extern HINSTANCE hLibrary;

#define LINK_ENTITY_TO_FUNC(mapClassName) \
	extern "C" EXPORT void mapClassName( entvars_t *pev ); \
	void mapClassName( entvars_t *pev ) { \
        static LINK_ENTITY_FUNC otherClassName = NULL; \
        static int skip = 0; \
		if( skip ) { return; } \
		if( otherClassName == NULL ) { otherClassName = (LINK_ENTITY_FUNC)GetProcAddress( hLibrary, #mapClassName ); } \
        if( otherClassName == NULL ) { skip = 1; return; } \
        (*otherClassName)( pev ); }

#define REMAP_ENTITY_TO_FUNC(remapClassName,mapClassName) \
	extern "C" EXPORT void remapClassName( entvars_t *pev ); \
	void remapClassName( entvars_t *pev ) { \
        static LINK_ENTITY_FUNC otherClassName = NULL; \
        static int skip = 0; \
		if( skip ) { return; } \
		if( otherClassName == NULL ) { otherClassName = (LINK_ENTITY_FUNC)GetProcAddress( hLibrary, #mapClassName ); } \
        if( otherClassName == NULL ) { skip = 1; return; } \
        (*otherClassName)( pev ); }

// entities for Valve's hl.dll and Standard SDK...
LINK_ENTITY_TO_FUNC(aiscripted_sequence);
LINK_ENTITY_TO_FUNC(ambient_generic);
LINK_ENTITY_TO_FUNC(ammo_357);
LINK_ENTITY_TO_FUNC(ammo_9mmAR);
LINK_ENTITY_TO_FUNC(ammo_9mmbox);
LINK_ENTITY_TO_FUNC(ammo_9mmclip);
LINK_ENTITY_TO_FUNC(ammo_ARgrenades);
LINK_ENTITY_TO_FUNC(ammo_buckshot);
LINK_ENTITY_TO_FUNC(ammo_crossbow);
LINK_ENTITY_TO_FUNC(ammo_egonclip);
LINK_ENTITY_TO_FUNC(ammo_gaussclip);
LINK_ENTITY_TO_FUNC(ammo_glockclip);
LINK_ENTITY_TO_FUNC(ammo_mp5clip);
LINK_ENTITY_TO_FUNC(ammo_mp5grenades);
LINK_ENTITY_TO_FUNC(ammo_rpgclip);
LINK_ENTITY_TO_FUNC(beam);
LINK_ENTITY_TO_FUNC(bmortar);
LINK_ENTITY_TO_FUNC(bodyque);
LINK_ENTITY_TO_FUNC(button_target);
LINK_ENTITY_TO_FUNC(cine_blood);
LINK_ENTITY_TO_FUNC(controller_energy_ball);
LINK_ENTITY_TO_FUNC(controller_head_ball);
LINK_ENTITY_TO_FUNC(crossbow_bolt);
LINK_ENTITY_TO_FUNC(cycler);
LINK_ENTITY_TO_FUNC(cycler_prdroid);
LINK_ENTITY_TO_FUNC(cycler_sprite);
LINK_ENTITY_TO_FUNC(cycler_weapon);
LINK_ENTITY_TO_FUNC(cycler_wreckage);
LINK_ENTITY_TO_FUNC(env_beam);
LINK_ENTITY_TO_FUNC(env_beverage);
LINK_ENTITY_TO_FUNC(env_blood);
LINK_ENTITY_TO_FUNC(env_bubbles);
LINK_ENTITY_TO_FUNC(env_debris);
LINK_ENTITY_TO_FUNC(env_explosion);
LINK_ENTITY_TO_FUNC(env_fade);
LINK_ENTITY_TO_FUNC(env_funnel);
LINK_ENTITY_TO_FUNC(env_global);
LINK_ENTITY_TO_FUNC(env_glow);
LINK_ENTITY_TO_FUNC(env_laser);
LINK_ENTITY_TO_FUNC(env_lightning);
LINK_ENTITY_TO_FUNC(env_message);
LINK_ENTITY_TO_FUNC(env_render);
LINK_ENTITY_TO_FUNC(env_shake);
LINK_ENTITY_TO_FUNC(env_shooter);
LINK_ENTITY_TO_FUNC(env_smoker);
LINK_ENTITY_TO_FUNC(env_sound);
LINK_ENTITY_TO_FUNC(env_spark);
LINK_ENTITY_TO_FUNC(env_sprite);
LINK_ENTITY_TO_FUNC(fireanddie);
LINK_ENTITY_TO_FUNC(func_breakable);
LINK_ENTITY_TO_FUNC(func_button);
LINK_ENTITY_TO_FUNC(func_conveyor);
LINK_ENTITY_TO_FUNC(func_door);
LINK_ENTITY_TO_FUNC(func_door_rotating);
LINK_ENTITY_TO_FUNC(func_friction);
LINK_ENTITY_TO_FUNC(func_guntarget);
LINK_ENTITY_TO_FUNC(func_healthcharger);
LINK_ENTITY_TO_FUNC(func_illusionary);
LINK_ENTITY_TO_FUNC(func_ladder);
LINK_ENTITY_TO_FUNC(func_monsterclip);
LINK_ENTITY_TO_FUNC(func_mortar_field);
LINK_ENTITY_TO_FUNC(func_pendulum);
LINK_ENTITY_TO_FUNC(func_plat);
LINK_ENTITY_TO_FUNC(func_platrot);
LINK_ENTITY_TO_FUNC(func_pushable);
LINK_ENTITY_TO_FUNC(func_recharge);
LINK_ENTITY_TO_FUNC(func_rot_button);
LINK_ENTITY_TO_FUNC(func_rotating);
LINK_ENTITY_TO_FUNC(func_tank);
LINK_ENTITY_TO_FUNC(func_tankcontrols);
LINK_ENTITY_TO_FUNC(func_tanklaser);
LINK_ENTITY_TO_FUNC(func_tankmortar);
LINK_ENTITY_TO_FUNC(func_tankrocket);
LINK_ENTITY_TO_FUNC(func_trackautochange);
LINK_ENTITY_TO_FUNC(func_trackchange);
LINK_ENTITY_TO_FUNC(func_tracktrain);
LINK_ENTITY_TO_FUNC(func_train);
LINK_ENTITY_TO_FUNC(func_traincontrols);
LINK_ENTITY_TO_FUNC(func_wall);
LINK_ENTITY_TO_FUNC(func_wall_toggle);
LINK_ENTITY_TO_FUNC(func_water);
LINK_ENTITY_TO_FUNC(game_counter);
LINK_ENTITY_TO_FUNC(game_counter_set);
LINK_ENTITY_TO_FUNC(game_end);
LINK_ENTITY_TO_FUNC(game_player_equip);
LINK_ENTITY_TO_FUNC(game_player_hurt);
LINK_ENTITY_TO_FUNC(game_player_team);
LINK_ENTITY_TO_FUNC(game_score);
LINK_ENTITY_TO_FUNC(game_team_master);
LINK_ENTITY_TO_FUNC(game_team_set);
LINK_ENTITY_TO_FUNC(game_text);
LINK_ENTITY_TO_FUNC(game_zone_player);
LINK_ENTITY_TO_FUNC(garg_stomp);
LINK_ENTITY_TO_FUNC(gibshooter);
LINK_ENTITY_TO_FUNC(grenade);
LINK_ENTITY_TO_FUNC(hornet);
LINK_ENTITY_TO_FUNC(hvr_rocket);
LINK_ENTITY_TO_FUNC(info_bigmomma);
LINK_ENTITY_TO_FUNC(info_intermission);
LINK_ENTITY_TO_FUNC(info_landmark);
LINK_ENTITY_TO_FUNC(info_node);
LINK_ENTITY_TO_FUNC(info_node_air);
LINK_ENTITY_TO_FUNC(info_null);
LINK_ENTITY_TO_FUNC(info_player_deathmatch);
LINK_ENTITY_TO_FUNC(info_player_start);
LINK_ENTITY_TO_FUNC(info_target);
LINK_ENTITY_TO_FUNC(info_teleport_destination);
LINK_ENTITY_TO_FUNC(infodecal);
LINK_ENTITY_TO_FUNC(item_airtank);
LINK_ENTITY_TO_FUNC(item_antidote);
LINK_ENTITY_TO_FUNC(item_battery);
LINK_ENTITY_TO_FUNC(item_healthkit);
LINK_ENTITY_TO_FUNC(item_longjump);
LINK_ENTITY_TO_FUNC(item_security);
LINK_ENTITY_TO_FUNC(item_sodacan);
LINK_ENTITY_TO_FUNC(item_suit);
LINK_ENTITY_TO_FUNC(laser_spot);
LINK_ENTITY_TO_FUNC(light);
LINK_ENTITY_TO_FUNC(light_environment);
LINK_ENTITY_TO_FUNC(light_spot);
LINK_ENTITY_TO_FUNC(momentary_door);
LINK_ENTITY_TO_FUNC(momentary_rot_button);
LINK_ENTITY_TO_FUNC(monster_alien_controller);
LINK_ENTITY_TO_FUNC(monster_alien_grunt);
LINK_ENTITY_TO_FUNC(monster_alien_slave);
LINK_ENTITY_TO_FUNC(monster_apache);
LINK_ENTITY_TO_FUNC(monster_babycrab);
LINK_ENTITY_TO_FUNC(monster_barnacle);
LINK_ENTITY_TO_FUNC(monster_barney);
LINK_ENTITY_TO_FUNC(monster_barney_dead);
LINK_ENTITY_TO_FUNC(monster_bigmomma);
LINK_ENTITY_TO_FUNC(monster_bloater);
LINK_ENTITY_TO_FUNC(monster_bullchicken);
LINK_ENTITY_TO_FUNC(monster_cine2_hvyweapons);
LINK_ENTITY_TO_FUNC(monster_cine2_scientist);
LINK_ENTITY_TO_FUNC(monster_cine2_slave);
LINK_ENTITY_TO_FUNC(monster_cine3_barney);
LINK_ENTITY_TO_FUNC(monster_cine3_scientist);
LINK_ENTITY_TO_FUNC(monster_cine_barney);
LINK_ENTITY_TO_FUNC(monster_cine_panther);
LINK_ENTITY_TO_FUNC(monster_cine_scientist);
LINK_ENTITY_TO_FUNC(monster_cockroach);
LINK_ENTITY_TO_FUNC(monster_flyer);
LINK_ENTITY_TO_FUNC(monster_flyer_flock);
LINK_ENTITY_TO_FUNC(monster_furniture);
LINK_ENTITY_TO_FUNC(monster_gargantua);
LINK_ENTITY_TO_FUNC(monster_generic);
LINK_ENTITY_TO_FUNC(monster_gman);
LINK_ENTITY_TO_FUNC(monster_grunt_repel);
LINK_ENTITY_TO_FUNC(monster_headcrab);
LINK_ENTITY_TO_FUNC(monster_hevsuit_dead);
LINK_ENTITY_TO_FUNC(monster_hgrunt_dead);
LINK_ENTITY_TO_FUNC(monster_houndeye);
LINK_ENTITY_TO_FUNC(monster_human_assassin);
LINK_ENTITY_TO_FUNC(monster_human_grunt);
LINK_ENTITY_TO_FUNC(monster_ichthyosaur);
LINK_ENTITY_TO_FUNC(monster_leech);
LINK_ENTITY_TO_FUNC(monster_miniturret);
LINK_ENTITY_TO_FUNC(monster_mortar);
LINK_ENTITY_TO_FUNC(monster_nihilanth);
LINK_ENTITY_TO_FUNC(monster_osprey);
LINK_ENTITY_TO_FUNC(monster_rat);
LINK_ENTITY_TO_FUNC(monster_satchel);
LINK_ENTITY_TO_FUNC(monster_scientist);
LINK_ENTITY_TO_FUNC(monster_scientist_dead);
LINK_ENTITY_TO_FUNC(monster_sentry);
LINK_ENTITY_TO_FUNC(monster_sitting_scientist);
LINK_ENTITY_TO_FUNC(monster_snark);
LINK_ENTITY_TO_FUNC(monster_tentacle);
LINK_ENTITY_TO_FUNC(monster_tentaclemaw);
LINK_ENTITY_TO_FUNC(monster_tripmine);
LINK_ENTITY_TO_FUNC(monster_turret);
LINK_ENTITY_TO_FUNC(monster_vortigaunt);
LINK_ENTITY_TO_FUNC(monster_zombie);
LINK_ENTITY_TO_FUNC(monstermaker);
LINK_ENTITY_TO_FUNC(multi_manager);
LINK_ENTITY_TO_FUNC(multisource);
LINK_ENTITY_TO_FUNC(nihilanth_energy_ball);
LINK_ENTITY_TO_FUNC(node_viewer);
LINK_ENTITY_TO_FUNC(node_viewer_fly);
LINK_ENTITY_TO_FUNC(node_viewer_human);
LINK_ENTITY_TO_FUNC(node_viewer_large);
LINK_ENTITY_TO_FUNC(path_corner);
LINK_ENTITY_TO_FUNC(path_track);
LINK_ENTITY_TO_FUNC(player);
LINK_ENTITY_TO_FUNC(player_loadsaved);
LINK_ENTITY_TO_FUNC(player_weaponstrip);
LINK_ENTITY_TO_FUNC(rpg_rocket);
LINK_ENTITY_TO_FUNC(scripted_sentence);
LINK_ENTITY_TO_FUNC(scripted_sequence);
LINK_ENTITY_TO_FUNC(soundent);
LINK_ENTITY_TO_FUNC(spark_shower);
LINK_ENTITY_TO_FUNC(speaker);
LINK_ENTITY_TO_FUNC(squidspit);
LINK_ENTITY_TO_FUNC(streak_spiral);
LINK_ENTITY_TO_FUNC(target_cdaudio);
LINK_ENTITY_TO_FUNC(test_effect);
LINK_ENTITY_TO_FUNC(testhull);
LINK_ENTITY_TO_FUNC(trigger);
LINK_ENTITY_TO_FUNC(trigger_auto);
LINK_ENTITY_TO_FUNC(trigger_autosave);
LINK_ENTITY_TO_FUNC(trigger_camera);
LINK_ENTITY_TO_FUNC(trigger_cdaudio);
LINK_ENTITY_TO_FUNC(trigger_changelevel);
LINK_ENTITY_TO_FUNC(trigger_changetarget);
LINK_ENTITY_TO_FUNC(trigger_counter);
LINK_ENTITY_TO_FUNC(trigger_endsection);
LINK_ENTITY_TO_FUNC(trigger_gravity);
LINK_ENTITY_TO_FUNC(trigger_hurt);
LINK_ENTITY_TO_FUNC(trigger_monsterjump);
LINK_ENTITY_TO_FUNC(trigger_multiple);
LINK_ENTITY_TO_FUNC(trigger_once);
LINK_ENTITY_TO_FUNC(trigger_push);
LINK_ENTITY_TO_FUNC(trigger_relay);
LINK_ENTITY_TO_FUNC(trigger_teleport);
LINK_ENTITY_TO_FUNC(trigger_transition);
LINK_ENTITY_TO_FUNC(weapon_357);
LINK_ENTITY_TO_FUNC(weapon_9mmAR);
LINK_ENTITY_TO_FUNC(weapon_9mmhandgun);
LINK_ENTITY_TO_FUNC(weapon_crossbow);
LINK_ENTITY_TO_FUNC(weapon_crowbar);
LINK_ENTITY_TO_FUNC(weapon_egon);
LINK_ENTITY_TO_FUNC(weapon_gauss);
LINK_ENTITY_TO_FUNC(weapon_glock);
LINK_ENTITY_TO_FUNC(weapon_handgrenade);
LINK_ENTITY_TO_FUNC(weapon_hornetgun);
LINK_ENTITY_TO_FUNC(weapon_mp5);
LINK_ENTITY_TO_FUNC(weapon_python);
LINK_ENTITY_TO_FUNC(weapon_rpg);
LINK_ENTITY_TO_FUNC(weapon_satchel);
LINK_ENTITY_TO_FUNC(weapon_shotgun);
LINK_ENTITY_TO_FUNC(weapon_snark);
LINK_ENTITY_TO_FUNC(weapon_tripmine);
LINK_ENTITY_TO_FUNC(weaponbox);
LINK_ENTITY_TO_FUNC(world_items);
LINK_ENTITY_TO_FUNC(worldspawn);
LINK_ENTITY_TO_FUNC(xen_hair);
LINK_ENTITY_TO_FUNC(xen_hull);
LINK_ENTITY_TO_FUNC(xen_plantlight);
LINK_ENTITY_TO_FUNC(xen_spore_large);
LINK_ENTITY_TO_FUNC(xen_spore_medium);
LINK_ENTITY_TO_FUNC(xen_spore_small);
LINK_ENTITY_TO_FUNC(xen_tree);
LINK_ENTITY_TO_FUNC(xen_ttrigger);

LINK_ENTITY_TO_FUNC(ammo_338magnum);
LINK_ENTITY_TO_FUNC(ammo_357sig);
LINK_ENTITY_TO_FUNC(ammo_45acp)
LINK_ENTITY_TO_FUNC(ammo_50ae);
LINK_ENTITY_TO_FUNC(ammo_556nato);
LINK_ENTITY_TO_FUNC(ammo_556natobox);
LINK_ENTITY_TO_FUNC(ammo_57mm);
LINK_ENTITY_TO_FUNC(ammo_66mm);
LINK_ENTITY_TO_FUNC(ammo_762nato);
LINK_ENTITY_TO_FUNC(ammo_762natobox);
LINK_ENTITY_TO_FUNC(ammo_9mm);
LINK_ENTITY_TO_FUNC(ammo_bomb);
LINK_ENTITY_TO_FUNC(ammo_generic);
LINK_ENTITY_TO_FUNC(ammo_lawsclip);
LINK_ENTITY_TO_FUNC(ammo_syringe);
LINK_ENTITY_TO_FUNC(bomb);
LINK_ENTITY_TO_FUNC(env_fog);
LINK_ENTITY_TO_FUNC(env_liveammoshooter);
LINK_ENTITY_TO_FUNC(env_missionfailure);
LINK_ENTITY_TO_FUNC(env_particle);
LINK_ENTITY_TO_FUNC(env_rain);
LINK_ENTITY_TO_FUNC(env_randomweather);
LINK_ENTITY_TO_FUNC(env_snow);
LINK_ENTITY_TO_FUNC(func_model_brush);
LINK_ENTITY_TO_FUNC(func_rain);
LINK_ENTITY_TO_FUNC(func_snow);
LINK_ENTITY_TO_FUNC(hostage_entity);
LINK_ENTITY_TO_FUNC(info_camera);
LINK_ENTITY_TO_FUNC(info_hostage_rescue);
LINK_ENTITY_TO_FUNC(item_armor);
LINK_ENTITY_TO_FUNC(item_generic);
LINK_ENTITY_TO_FUNC(item_healthkitold);
LINK_ENTITY_TO_FUNC(item_worldmap);
LINK_ENTITY_TO_FUNC(laws_rocket);
LINK_ENTITY_TO_FUNC(monster_counter_terrorist_gign);
LINK_ENTITY_TO_FUNC(monster_counter_terrorist_gsg9);
LINK_ENTITY_TO_FUNC(monster_counter_terrorist_repel);
LINK_ENTITY_TO_FUNC(monster_counter_terrorist_sas);
LINK_ENTITY_TO_FUNC(monster_counter_terrorist_spetsnaz);
LINK_ENTITY_TO_FUNC(monster_counter_terrorist_swat);
LINK_ENTITY_TO_FUNC(monster_ct);
LINK_ENTITY_TO_FUNC(monster_ct_dead);
LINK_ENTITY_TO_FUNC(monster_ct_gign);
LINK_ENTITY_TO_FUNC(monster_ct_gign_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_ct_gign_grenader);
LINK_ENTITY_TO_FUNC(monster_ct_gign_law);
LINK_ENTITY_TO_FUNC(monster_ct_gign_machinegun);
LINK_ENTITY_TO_FUNC(monster_ct_gign_mp5);
LINK_ENTITY_TO_FUNC(monster_ct_gign_pistol);
LINK_ENTITY_TO_FUNC(monster_ct_gign_shotgun);
LINK_ENTITY_TO_FUNC(monster_ct_gign_smg);
LINK_ENTITY_TO_FUNC(monster_ct_gign_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_grenader);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_law);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_machinegun);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_mp5);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_pistol);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_shotgun);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_smg);
LINK_ENTITY_TO_FUNC(monster_ct_gsg9_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_ct_repel);
LINK_ENTITY_TO_FUNC(monster_ct_sas);
LINK_ENTITY_TO_FUNC(monster_ct_sas_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_ct_sas_grenader);
LINK_ENTITY_TO_FUNC(monster_ct_sas_law);
LINK_ENTITY_TO_FUNC(monster_ct_sas_machinegun);
LINK_ENTITY_TO_FUNC(monster_ct_sas_mp5);
LINK_ENTITY_TO_FUNC(monster_ct_sas_pistol);
LINK_ENTITY_TO_FUNC(monster_ct_sas_shotgun);
LINK_ENTITY_TO_FUNC(monster_ct_sas_smg);
LINK_ENTITY_TO_FUNC(monster_ct_sas_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_grenader);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_law);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_machinegun);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_mp5);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_pistol);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_shotgun);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_smg);
LINK_ENTITY_TO_FUNC(monster_ct_spetsnaz_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_ct_swat);
LINK_ENTITY_TO_FUNC(monster_ct_swat_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_ct_swat_grenader);
LINK_ENTITY_TO_FUNC(monster_ct_swat_law);
LINK_ENTITY_TO_FUNC(monster_ct_swat_machinegun);
LINK_ENTITY_TO_FUNC(monster_ct_swat_mp5);
LINK_ENTITY_TO_FUNC(monster_ct_swat_pistol);
LINK_ENTITY_TO_FUNC(monster_ct_swat_shotgun);
LINK_ENTITY_TO_FUNC(monster_ct_swat_smg);
LINK_ENTITY_TO_FUNC(monster_ct_swat_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_hostage);
LINK_ENTITY_TO_FUNC(monster_npc);
LINK_ENTITY_TO_FUNC(monster_npc_dead);
LINK_ENTITY_TO_FUNC(monster_sitting_npc);
LINK_ENTITY_TO_FUNC(monster_t);
LINK_ENTITY_TO_FUNC(monster_t_arctic);
LINK_ENTITY_TO_FUNC(monster_t_arctic_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_t_arctic_grenader);
LINK_ENTITY_TO_FUNC(monster_t_arctic_kamakazi);
LINK_ENTITY_TO_FUNC(monster_t_arctic_law);
LINK_ENTITY_TO_FUNC(monster_t_arctic_machinegun);
LINK_ENTITY_TO_FUNC(monster_t_arctic_melee);
LINK_ENTITY_TO_FUNC(monster_t_arctic_mp5);
LINK_ENTITY_TO_FUNC(monster_t_arctic_pistol);
LINK_ENTITY_TO_FUNC(monster_t_arctic_shotgun);
LINK_ENTITY_TO_FUNC(monster_t_arctic_smg);
LINK_ENTITY_TO_FUNC(monster_t_arctic_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_t_asian);
LINK_ENTITY_TO_FUNC(monster_t_asian_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_t_asian_grenader);
LINK_ENTITY_TO_FUNC(monster_t_asian_kamakazi);
LINK_ENTITY_TO_FUNC(monster_t_asian_law);
LINK_ENTITY_TO_FUNC(monster_t_asian_machinegun);
LINK_ENTITY_TO_FUNC(monster_t_asian_melee);
LINK_ENTITY_TO_FUNC(monster_t_asian_mp5);
LINK_ENTITY_TO_FUNC(monster_t_asian_pistol);
LINK_ENTITY_TO_FUNC(monster_t_asian_shotgun);
LINK_ENTITY_TO_FUNC(monster_t_asian_smg);
LINK_ENTITY_TO_FUNC(monster_t_asian_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_t_dead);
LINK_ENTITY_TO_FUNC(monster_t_desert);
LINK_ENTITY_TO_FUNC(monster_t_desert_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_t_desert_grenader);
LINK_ENTITY_TO_FUNC(monster_t_desert_kamakazi);
LINK_ENTITY_TO_FUNC(monster_t_desert_law);
LINK_ENTITY_TO_FUNC(monster_t_desert_machinegun);
LINK_ENTITY_TO_FUNC(monster_t_desert_melee);
LINK_ENTITY_TO_FUNC(monster_t_desert_mp5);
LINK_ENTITY_TO_FUNC(monster_t_desert_pistol);
LINK_ENTITY_TO_FUNC(monster_t_desert_shotgun);
LINK_ENTITY_TO_FUNC(monster_t_desert_smg);
LINK_ENTITY_TO_FUNC(monster_t_desert_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_t_jungle);
LINK_ENTITY_TO_FUNC(monster_t_jungle_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_t_jungle_grenader);
LINK_ENTITY_TO_FUNC(monster_t_jungle_kamakazi);
LINK_ENTITY_TO_FUNC(monster_t_jungle_law);
LINK_ENTITY_TO_FUNC(monster_t_jungle_machinegun);
LINK_ENTITY_TO_FUNC(monster_t_jungle_melee);
LINK_ENTITY_TO_FUNC(monster_t_jungle_mp5);
LINK_ENTITY_TO_FUNC(monster_t_jungle_pistol);
LINK_ENTITY_TO_FUNC(monster_t_jungle_shotgun);
LINK_ENTITY_TO_FUNC(monster_t_jungle_smg);
LINK_ENTITY_TO_FUNC(monster_t_jungle_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_t_repel);
LINK_ENTITY_TO_FUNC(monster_t_russian);
LINK_ENTITY_TO_FUNC(monster_t_russian_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_t_russian_grenader);
LINK_ENTITY_TO_FUNC(monster_t_russian_kamakazi);
LINK_ENTITY_TO_FUNC(monster_t_russian_law);
LINK_ENTITY_TO_FUNC(monster_t_russian_machinegun);
LINK_ENTITY_TO_FUNC(monster_t_russian_melee);
LINK_ENTITY_TO_FUNC(monster_t_russian_mp5);
LINK_ENTITY_TO_FUNC(monster_t_russian_pistol);
LINK_ENTITY_TO_FUNC(monster_t_russian_shotgun);
LINK_ENTITY_TO_FUNC(monster_t_russian_smg);
LINK_ENTITY_TO_FUNC(monster_t_russian_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_t_urban);
LINK_ENTITY_TO_FUNC(monster_t_urban_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_t_urban_grenader);
LINK_ENTITY_TO_FUNC(monster_t_urban_kamakazi);
LINK_ENTITY_TO_FUNC(monster_t_urban_law);
LINK_ENTITY_TO_FUNC(monster_t_urban_machinegun);
LINK_ENTITY_TO_FUNC(monster_t_urban_melee);
LINK_ENTITY_TO_FUNC(monster_t_urban_mp5);
LINK_ENTITY_TO_FUNC(monster_t_urban_pistol);
LINK_ENTITY_TO_FUNC(monster_t_urban_shotgun);
LINK_ENTITY_TO_FUNC(monster_t_urban_smg);
LINK_ENTITY_TO_FUNC(monster_t_urban_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_grenader);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_kamakazi);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_law);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_machinegun);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_melee);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_mp5);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_pistol);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_shotgun);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_smg);
LINK_ENTITY_TO_FUNC(monster_terrorist_arctic_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_grenader);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_kamakazi);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_law);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_machinegun);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_melee);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_mp5);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_pistol);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_shotgun);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_smg);
LINK_ENTITY_TO_FUNC(monster_terrorist_asian_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_dead);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_grenader);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_kamakazi);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_law);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_machinegun);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_melee);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_mp5);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_pistol);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_shotgun);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_smg);
LINK_ENTITY_TO_FUNC(monster_terrorist_desert_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_grenader);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_kamakazi);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_law);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_machinegun);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_melee);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_mp5);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_pistol);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_shotgun);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_smg);
LINK_ENTITY_TO_FUNC(monster_terrorist_jungle_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_repel);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_grenader);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_kamakazi);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_law);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_machinegun);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_melee);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_mp5);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_pistol);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_shotgun);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_smg);
LINK_ENTITY_TO_FUNC(monster_terrorist_russian_sniperrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_assaultrifle);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_grenader);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_kamakazi);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_law);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_machinegun);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_melee);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_mp5);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_pistol);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_shotgun);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_smg);
LINK_ENTITY_TO_FUNC(monster_terrorist_urban_sniperrifle);
LINK_ENTITY_TO_FUNC(trigger_changekeyvalue);
LINK_ENTITY_TO_FUNC(trigger_endmission);
LINK_ENTITY_TO_FUNC(trigger_freezeplayer);
LINK_ENTITY_TO_FUNC(trigger_hud);
LINK_ENTITY_TO_FUNC(trigger_incognito);
LINK_ENTITY_TO_FUNC(trigger_killtarget);
LINK_ENTITY_TO_FUNC(trigger_objective);
LINK_ENTITY_TO_FUNC(trigger_sequence);
LINK_ENTITY_TO_FUNC(trigger_stealth);
LINK_ENTITY_TO_FUNC(trigger_usetool);
LINK_ENTITY_TO_FUNC(trigger_zipline);
LINK_ENTITY_TO_FUNC(weapon_ak47);
LINK_ENTITY_TO_FUNC(weapon_aug);
LINK_ENTITY_TO_FUNC(weapon_awp);
LINK_ENTITY_TO_FUNC(weapon_blowtorch);
LINK_ENTITY_TO_FUNC(weapon_briefcase);
LINK_ENTITY_TO_FUNC(weapon_c4);
LINK_ENTITY_TO_FUNC(weapon_camera);
LINK_ENTITY_TO_FUNC(weapon_deagle);
LINK_ENTITY_TO_FUNC(weapon_effectspoint);
LINK_ENTITY_TO_FUNC(weapon_elite);
LINK_ENTITY_TO_FUNC(weapon_famas);
LINK_ENTITY_TO_FUNC(weapon_fiberopticcamera);
LINK_ENTITY_TO_FUNC(weapon_fiveseven);
LINK_ENTITY_TO_FUNC(weapon_flashbang);
LINK_ENTITY_TO_FUNC(weapon_g3sg1);
LINK_ENTITY_TO_FUNC(weapon_galil);
LINK_ENTITY_TO_FUNC(weapon_glock18);
LINK_ENTITY_TO_FUNC(weapon_hegrenade);
LINK_ENTITY_TO_FUNC(weapon_knife);
LINK_ENTITY_TO_FUNC(weapon_laws);
LINK_ENTITY_TO_FUNC(weapon_m249);
LINK_ENTITY_TO_FUNC(weapon_m3);
LINK_ENTITY_TO_FUNC(weapon_m4a1);
LINK_ENTITY_TO_FUNC(weapon_m60);
LINK_ENTITY_TO_FUNC(weapon_mac10);
LINK_ENTITY_TO_FUNC(weapon_medkit);
LINK_ENTITY_TO_FUNC(weapon_mp5navy);
LINK_ENTITY_TO_FUNC(weapon_p228);
LINK_ENTITY_TO_FUNC(weapon_p90);
LINK_ENTITY_TO_FUNC(weapon_radio);
LINK_ENTITY_TO_FUNC(weapon_radiocontrolledbomb);
LINK_ENTITY_TO_FUNC(weapon_scout);
LINK_ENTITY_TO_FUNC(weapon_sg550);
LINK_ENTITY_TO_FUNC(weapon_sg552);
LINK_ENTITY_TO_FUNC(weapon_shieldgun);
LINK_ENTITY_TO_FUNC(weapon_smokegrenade);
LINK_ENTITY_TO_FUNC(weapon_tmp);
LINK_ENTITY_TO_FUNC(weapon_ump45);
LINK_ENTITY_TO_FUNC(weapon_usp);
LINK_ENTITY_TO_FUNC(weapon_xm1014);
LINK_ENTITY_TO_FUNC(weapon_zipline);

// probably already aliased in cz.dll
// REMAP_ENTITY_TO_FUNC(monster_ct_repel, monster_counter_terrorist_repel);
// REMAP_ENTITY_TO_FUNC(monster_ct_spetznaz, monster_counter_terrorist_spetsnaz);

REMAP_ENTITY_TO_FUNC(monster_ct_spetsnaz_ar, monster_ct_spetsnaz_assaultrifle);
REMAP_ENTITY_TO_FUNC(monster_ct_spetsnaz_sniper, monster_ct_spetsnaz_sniperrifle);
#if 0
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_assaultrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_grenader);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_kamikaze);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_machinegun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_pistol);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_shotgun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_arctic_sniperrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_assaultrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_grenader);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_kamikaze);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_machinegun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_pistol);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_shotgun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_desert_sniperrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_assaultrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_grenader);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_kamikaze);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_machinegun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_pistol);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_shotgun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_jungle_sniperrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_assaultrifle);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_grenader);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_kamikaze);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_machinegun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_melee);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_pistol);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_shotgun);
REMAP_ENTITY_TO_FUNC( ,monster_terrorist_russian_sniperrifle);
#endif